### ISSUE TITLE
Expose Q through Q-IO

### ISSUE THREAD

**Issue by jiggliemon** [kriskowal/q-io#105]
Q should be accessible through Q-IO.

``` js
var Q = require('q-io').Q;
```

This will prevent the user from having a dependency on both the `Q` and `Q-IO` Libraries.

**Comment by anton-rudeshko** [comment]
**_+1**_ here
You can use a workaround: `var q = require('q-io/node_modules/q')`

**Comment by anton-rudeshko** [comment]
> This will prevent the user from having a dependency on both the Q and Q-IO Libraries.

BTW, this is not true, because Q-IO will reuse existing compatible Q if any

**Comment by fineline** [comment]
+1, seems a bit redundant to have to depend on both. Can you clarify what you mean anton. When you npm install q-io it will bring in q sub-module regardless, I think?

**Comment by anton-rudeshko** [comment]
> it will bring in q sub-module regardless

No, npm will reuse app level q if it compatible.

For example:
Let `q-io@1.2.1` depend on `q@~1.0.1`. When you `npm install` an app with package.json as such:

``` json
{
  "dependencies": {
    "q": "~1.0.1",
    "q-io": "~1.2.1"
  }
}
```

then q-io will use q in your app `node_modules` dir and wouldn't have another one in `node_modules/q-io/node_modules`. It holds true only if you have compatible q version.

**Comment by fineline** [comment]
OK thanks Anton, didn't know that.

**Comment by kriskowal** [comment]
I’m opting not to introduce this change. Q and Q-IO are separate but interdependent. npm handles all of the cases gracefully. I believe consuming packages should be explicit about this dependency, especially to elevate the shared dependency to avoid duplication.

**Comment by anton-rudeshko** [comment]
We respect your choice, Kris. Thank you!
