### ISSUE TITLE
What is this buffer I'm getting from the promised return of q-http.read?

### ISSUE THREAD

**Issue by funkjunky** [kriskowal/q-io#117]
I've been slowly getting a worst and worst headache trying to figure out what to do with this <buffer octat octat octat> I'm getting from the return of this function. I was hoping some string data to be returned, but instead I get this buffer, which doesn't appear to be an object i can do anything with.

From your documentation it says it's supposed to be a response object, but it's not :(
EDIT: I just tried using request, then response.body.read().then(function(data) { console.log(data); and I still got a buffer back T_T

**Comment by Stuk** [comment]
I believe it is a Node Buffer. To get a string you can call .toString("utf8") on it.

**Comment by funkjunky** [comment]
thanks :). Ya just before reading this I decided to try JSON.parse'ing the data and it came out correctly. So I guess it was the correct data, just no wrapped in the correct object. I haven't done a lot of node, but i've done a lot of front-end JS... I suppose this is one of those differences that can screw me =P [Your toString suggestion is perfect for next time, because if there was even the slightest error in the JSON, I would have still been in the dark]

Sorry to pollute your issues list, feel free to remove this issue if you want. it's just my n00bness with nodejs.
