### ISSUE TITLE
Negotiator HTTP apps do not specify a response argument

### ISSUE THREAD

**Issue by trevorparscal** [kriskowal/q-io#118]
Using a Negotiator HTTP App, like ContentType, fails because of a missing argument in the method signature of the returned application function.

**Comment by trevorparscal** [comment]
I'm noticing a lot of cases in the code, especially as I try and use it, where request and response are listed in reverse order, or only response is listed causing essentially the same issue. Are you open to pull-requests that correct these many inconsistencies?

**Comment by kriskowal** [comment]
Some of these cases are deliberate. Feel free to point out the cases that
are contentious and I’d be glad to explain each. At some point, I could use
some help shoring up the documentation.

**Comment by trevorparscal** [comment]
There are instances of Q.when( app, function ( response ) {} ) that make sense, but take HttpApps.Trap, where you reverse the order of request and response - what is going on there?

**Comment by kriskowal** [comment]
That was an ergonomic decision. Traps usually only work with the response
and either return it or replace it. The request is not always useful for
traps, but provided in case it is needed.
