### ISSUE TITLE
[fs-mock] Mock.move shouldn't move source into target, if target is a directory.

### ISSUE THREAD

**Issue by francoisfrisch** [kriskowal/q-io#13]
Mock.move moves the source node into the target node if the target node is a directory. This doesn't match the real fs implementation that uses FS.rename .

In this case, Mock.move should move all the contents of source into target.

**Comment by francoisfrisch** [comment]
Alternatively, we could also file a bug against the q-io move since it probably shouldn't mimic all of the behaviors of  FS.rename .

**Comment by kriskowal** [comment]
I’ve never liked clever "move" implementations. My thought is that both `fs` and `fs-mock` should move a single file or directory such that it becomes available at the target path, or die trying. It should not move multiple files from one directory to another, nor should it put a file inside a target directory.  If the target exists, regardless of type, it should fail.

Unless I’m mistaken, neither implementation matches this contract.
