### ISSUE TITLE
proxy requests

### ISSUE THREAD

**Issue by thabti** [kriskowal/q-io#130]
Hi, 

So our internal cloud allows external calls via a proxy server, how can I tell q-io to use environment variable of the proxy server host and port ?

**Comment by Stuk** [comment]
Because Q-IO is just using `http.request` under the hood, you should be able to follow [this StoackOverflow answer](http://stackoverflow.com/a/6366629):

``` js
http.request({
    hostname: '127.0.0.1:8888', // your proxy
    path: 'http://example.com/' // the URL you actually want to get
}).then(function (response) {
    console.log(response);
});
```

I haven't actually tried this, so let me know how it goes.

**Comment by kriskowal** [comment]
`hostname + ":" + port = host`. You can use either hostname and port, or just host. To write a full-fledged HTTP proxy, you would parse these out of the received request.path and forward the domain relative path to the proxied server, but that may or may not be your intent.
