### ISSUE TITLE
Mock: fs.copy() is buggy

### ISSUE THREAD

**Issue by c-geek** [kriskowal/q-io#146]
Hi there! First, thanks a lot for your work. I'm a fan :-)

I just wanted to warn you that I had weird code behavior while using `fs.copy()` in mock mode: a copied file content suddently becomes empty at some point in my unit tests.

I am sorry I can't give you a clear & simple unit test right now, I just see it in my business test case.

I can tell you I have this since I do not have any issue while using `fs.read()` + `fs.write()` combo instead of `fs.copy()`, and `fs.copy()` is also greatly working using real file system mode.

This bug is at least present in versions `1.12.0` and `1.13.1`. I am using Ubuntu 14.04 LTS x64.

If I have any time to write you a clear unit test, be sure I will.

Kindly.

**Comment by hthetiot** [comment]
Should be fixed in 1.13.3 @c-geek feel free to re-open otherwise.
- https://github.com/kriskowal/q-io/pull/161
