### ISSUE TITLE
[fs-mock] MockFs.makeDirectory shouldn't throw if the directory exists

### ISSUE THREAD

**Issue by francoisfrisch** [kriskowal/q-io#15]
The real implementation of makeDirectory rejects the promise with a reason code of "EEXIST" the mock throws.

This breaks MockFs.makeTree if some of the path already exists.

**Comment by kriskowal** [comment]
This is a bug in MockFs.makeTree. makeDirectory should fail if the target directory already exists.

**Comment by francoisfrisch** [comment]
copyTree also uses makeDirectory, there may be a problem there too.

**Comment by kriskowal** [comment]
What’s the expected behavior of copyTree if the target already exists? I think it should fail.

**Comment by francoisfrisch** [comment]
If copyTree fails if the target exists that would be consistent with the proposed makeTree behavior.

**Comment by francoisfrisch** [comment]
Sorry go that wrong was referring to the changes to move #13
