### ISSUE TITLE
Bump version of collections to avoid conflict with ES6

### ISSUE THREAD

**Issue by scandox** [kriskowal/q-io#151]
I ran into a hard to diagnose problem using `harmony` with node 4.2.1. In the end I figured out it was the version of `collections` being used by q-io, which was bundled with https://github.com/SLaks/Styliner 

The native `find` function is overwritten by the one in collections, which appears to actually fulfill the function of `findIndex`. Anyway I updated collections to version 2.0.2 and nothing obvious broke. I know it probably isn't that straightforward...but once ES6 is widespread it is going to come up a bit.

**Comment by kriskowal** [comment]
Please try q-io@2 from the v2 branch. It has the collections upgrade.

**Comment by scandox** [comment]
Ok sorry didn't see that. I'll raise an issue with the Styliner repo and see if they can move to the v2 branch.

Thanks.

**Comment by arikon** [comment]
@kriskowal `q-io@2` depends on `q@2` which is still experimental. Am I right?
