### ISSUE TITLE
MockFs.move inconsistency

### ISSUE THREAD

**Issue by francoisfrisch** [kriskowal/q-io#18]
Given and existing directory _myDirectory_
Doing 

``` javascript
fs.move("myDirectory", "myDirectory")
```

will throw "Can't move over existing entry myDirectory"
where as doing

``` javascript
MockFs.move("myDirectory", "myDirectory")
```

will succeed.

I'm unsure which one is correct. The fs behavior is strictly correct and might catch potential errors earlier but the mock behavior is much more convenient!

I tried simply removing the equality checks @ line 271 and 303 but it cause some test failures for symlink handling.

**Comment by kriskowal** [comment]
Thanks, François, fixed in patch version 1.5.2.
