### ISSUE TITLE
lastModified() generates an unhandled rejected promise warning

### ISSUE THREAD

**Issue by scf2k** [kriskowal/q-io#27]
`lastModified()` generates an unhandled rejected promise warning on program exist nevertheless the call has `.fail()` handler. Example to reproduce:

``` javascript
var QFS = require('q-io/fs');

QFS.lastModified('/nonexistent')
.fail(function(err) {
    console.log('error caught!');
});
```

**Comment by Stuk** [comment]
What do you expect to happen?

It seems to me that this is expected behaviour, although the spec doesn't say what should be done if the file does not exist http://wiki.commonjs.org/wiki/Filesystem/A/0#Attributes

**Comment by scf2k** [comment]
The problem is that I catch the error (with fail). But when application exits Q dumps a bunch of warnings that those rejected promises were NOT handled.

**Comment by arikon** [comment]
@scf2k Should move this issues to `q`

**Comment by scf2k** [comment]
moved https://github.com/kriskowal/q/issues/238

**Comment by Stuk** [comment]
Ah I see, sorry, misread it. Yep, Q is the best place for this.
