### ISSUE TITLE
Cannot serve binaries with Apps.file

### ISSUE THREAD

**Issue by danielfagerstrom** [kriskowal/q-io#29]
When I try to serve images with `Apps.file` they are encoded with UTF-8 (and stops being images).

This is because `FS.open` is called without flags or charset: https://github.com/kriskowal/q-io/blob/master/http-apps/fs.js#L128 and the default behavior for `FS.open` is to use charset UTF-8 when no flags are set https://github.com/kriskowal/q-io/blob/master/fs.js#L79 which in turn makes the reader join the results with `.join("")` https://github.com/kriskowal/q-io/blob/master/reader.js#L47.

Image serving worked before, but default behavior for `FS.open` was changed some while ago (by mistake?) without any comment https://github.com/kriskowal/q-io/commit/fbb217765182b99180909923c197ded50ba424a6#L5R80.

This could be fixed by either revert the default behavior of `FS.open` or by adding a binary flag to its use in `Apps.file`.

**Comment by kriskowal** [comment]
Thanks, looking into this now.
