### ISSUE TITLE
Feature: Make q-io/fs more graceful (workaround EMFILE errors)

### ISSUE THREAD

**Issue by dhbaird** [kriskowal/q-io#44]
I would like to request consideration of using [graceful-fs](https://github.com/isaacs/node-graceful-fs) rather than fs, in particular to avoid EMFILE errors like [this one](http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files).

Here is one thought about how to implement this:

```
var FS = require('q-io/fs'); // <-- if user wants standard fs
var GFS = require('q-io/graceful-fs'); // <-- if user wants graceful-fs
```

Alternatively, would it be feasible to implement "graceful" functionality directly in q-io/fs? (by retrying operations that fail with EMFILE, for instance, like graceful-fs does)

(Btw, thanks for this awesome library. It's terrific!)

**Comment by kriskowal** [comment]
We could add retry options to "open".

**Comment by dhbaird** [comment]
Hey, I just pulled this little gem out of q-io/fs.js, and it is already applied to readdir and open. How about that? Awesome :) I think that closes this ticket for now.

``` javascript
// facilitates AIMD (additive increase, multiplicative decrease) for backing off
var backOffDelay = 0;
var backOffFactor = 1.0001;
function dampen(wrapped, thisp) {
    var retry = function () {
        var args = arguments;
        var ready = backOffDelay ? Q.delay(backOffDelay) : Q.resolve();
        return ready.then(function () {
            return Q.when(wrapped.apply(thisp, args), function (stream) {
                backOffDelay = Math.max(0, backOffDelay - 1);
                return stream; 
            }, function (error) {
                if (error.code === "EMFILE") {
                    backOffDelay = (backOffDelay + 1) * backOffFactor;
                    return retry.apply(null, args);
                } else {
                    throw error;
                }   
            });
        });
    };
    return retry;
}         
```

**Comment by kriskowal** [comment]
Oh, right, I already did it!
