### ISSUE TITLE
move(src,tar) does not work between network shares

### ISSUE THREAD

**Issue by noppsen** [kriskowal/q-io#48]
You have to manually replace
  move(src, tar)
by 
  copyTree(src, tar)
  removeTree(src, tar)
since you are intended to use it with different network shares.

best regards and thanks

-------occurrence------------
- windows 7
- node 0.8

**Comment by kriskowal** [comment]
@noppsen I have addressed this with changes to move and rename, which have been released. Sorry for failing to get back to you. Please reopen if the issue persists.
