### ISSUE TITLE
Empty file in FS.stat or FS.read directly after FS.write

### ISSUE THREAD

**Issue by Bartvds** [kriskowal/q-io#52]
I have a weird case where a FS.write succeeds but the next FS.stat or FS.read on that file return zero-size (or empty file content). When I open the file in my editor I do see the expected content. 

Of course usually you wouldn't read same file instantly after you write it but this happens in my unit tests.

This only happens if the call to FS.stat or FS.read is very close behind the FS.write.

If I replace FS.stat with a node.js wrapper, like: `Q.nfcall(fs.stat, file)` I get the same behaviour.

If I put a some other promises between the write and reads (like a bunch chaining then()'s with some FS.stats on same file) then later the file checks out correctly. 

If I replace those filler FS.stats with a Q.delay(100) and then check I do get the empty file again.

So it looks like there is something going on with the filesystem: is there some sort of stat caching behaviour going on in Q-io or Node?

This is in node 0.10.17, on Windows vista 64 and also on a Ubuntu VM using Vagrant.

**Comment by kriskowal** [comment]
There’s no Stat cache in Q-IO; we call into Node.js directly and just wrap `stat` with a promise. I find it unlikely that Node.js has a cache either. However, if there were a cache at either layer, I think you could expect the stat to be up-to-date immediately (having been found in the cache), and the new problem would be how to invalidate that cache if another process changes the file system. We could conceivably fix the problem if the user expressed that they were sure that they were the only program touching a branch of the file system and introduce caching in that case, but that’s more complexity than I’m willing to take on.

It is very likely that this is an issue with the underlying operating system and file system, but, as they say, [select is not broken](http://pragmatictips.com/26).

**Comment by Bartvds** [comment]
Thanks for the info. 

I'm on windows which has the occasional issue with node so it is hard to be 100% sure it is my own code or not (what I'm doing looks so simple...  :)  

But at least we can assume the problem is not in q-io. I'll close this for now.
