### ISSUE TITLE
Reader.forEach() does not support thisp

### ISSUE THREAD

**Issue by JPGygax68** [kriskowal/q-io#58]
The signature of Reader.forEach() is not consistent with the same method in the BufferStream class. The latter supports a second argument "thisp", the former does not.

**Comment by kriskowal** [comment]
Thanks, @JPGygax68. This should be addressed in #57, which is pending on issues with paused readers and closing servers.

**Comment by kriskowal** [comment]
This is addressed in the v2 branch.
