### ISSUE TITLE
Writer.write() relies on the fact that stream.wirte() call is synchronous

### ISSUE THREAD

**Issue by scf2k** [kriskowal/q-io#59]
The `Writer.write()` method calls `stream.write()` as it is synchronous. This is true for `node 0.8`, but it's not for `0.10`. It expects a callback which is called when the data is flushed.

As result with `node 0.10` `QFS.write()` could resolve before file is actually written.

**Comment by kriskowal** [comment]
We may have addressed this in the most recent release, v1.10.2. Can you attempt to verify?

https://github.com/kriskowal/q-io/commit/a151a46df326d13c74e8a06b6e2a9727e57ae014

**Comment by arikon** [comment]
@kriskowal `Writable.write()` still returns resolved promise just after sync call to `stream.write()`.

https://github.com/kriskowal/q-io/blob/a151a46df326d13c74e8a06b6e2a9727e57ae014/writer.js#L55-59

**Comment by kriskowal** [comment]
Ah. Need a PR for that then. And that fix needs to be applied to the streams branch as well, which I will land soon.

**Comment by arikon** [comment]
@kriskowal I'm sorry. `fs.write()` returns the promise of `stream.close()`, and commit you pointed to fixes `stream.close()`. So it should be fixed now. We'll check.

**Comment by scf2k** [comment]
Seems to work with 1.10.2.
