### ISSUE TITLE
How can I copy a stream using promises?

### ISSUE THREAD

**Issue by joe-spanning** [kriskowal/q-io#68]
I have a readable stream that I would normally pipe into a writable stream.

``` javascript
readable.pipe(writable);
```

How can I achieve the same "copying" of streams using q-io?

**Comment by kriskowal** [comment]
There is a `readable.copy` method coming with promise streams in the next major release. In the interim, however, this should do the job:

``` js
readable.forEach(function (chunk) {
    return writable.write(chunk);
}).finally(function () {
    return writable.close();
});
```

**Comment by kriskowal** [comment]
I would amend:

``` js
readable.forEach(writable.write, writable)
.then(function () {
    writable.close();
}, function (error) {
    writable.destroy();
    throw error;
})
```

And again, in the v2 branch (which will not be recommended for consumption for a while), the interface is `readable.copy(writable)`, but I will probably introduce pipe methods, either compatible with Node or W3C streams. Would love to coordinate with @domenic on that front. v2 branch is relatively flexible.
