### ISSUE TITLE
Document that there is no main module

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/q-io#7]
Per #6, there is an expectation that q-io exports a main module. Update the documentation to make it more clear that there is no main module, and the names of the public modules in the Q-IO namespace, `q-io/fs`, `q-io/http`, and `q-io/http-apps`.

**Comment by boxxxie** [comment]
this seems very weird.
would you accept PRs with a main + file that exposes all of the Q libs?

also would you be able to point me in the direction of example uses of Q-http-app?

**Comment by kriskowal** [comment]
Thank you, but no. I would prefer to encourage folks to load only the modules they are likely to need. The Node `fs` and `http` modules are separate, so by analogy, these wrappers are separate.

HTTP Apps were originally in a [separate repository](https://github.com/kriskowal/jaque#readme). I’ll migrate the documentation over.

I wrote a routing library based on Q HTTP apps called [Joey](https://github.com/kriskowal/joey#joey).

**Comment by boxxxie** [comment]
can you give me an example of how i would load the http module without writing my own main file?

am i supposed to do something like require('./node_modules/q-io/http.js')?

**Comment by kriskowal** [comment]
In your module:

``` javascript
var HTTP = require("q-io/http");
```

And in your `package.json`:

``` json
{
    "dependencies": {
        "q-io": "1.3.2 - 2"
    }
}
```

**Comment by boxxxie** [comment]
oh wow, i didn't know i could do that!

**Comment by kriskowal** [comment]
Documented.
