### ISSUE TITLE
Undefnied agent causes error in node's HTTP module

### ISSUE THREAD

**Issue by kornelski** [kriskowal/q-io#71]
HTTP `read()` function fails when given string URLs:

```
 require('q-io/http').read('http://example.com').done()
```

> TypeError: Cannot read property 'defaultPort' of undefined
>     at new ClientRequest (_http_client.js:50:54)
>     at Agent.request (_http_agent.js:301:10)
>     at Object.exports.request (http.js:52:22)
>     at ./node_modules/q-io/http.js:295:29
>     at _fulfilled (./node_modules/q/q.js:798:54)
>     at self.promiseDispatch.done (./node_modules/q/q.js:827:30)
>     at Promise.promise.promiseDispatch (./node_modules/q/q.js:760:13)
>     at ./node_modules/q/q.js:821:14
>     at flush (./node_modules/q/q.js:108:17)
>     at process._tickCallback (node.js:598:11)

This may be because node doesn't handle `undefined` agent:

```
 require('http').request({agent:undefined})
```

> TypeError: Cannot read property 'defaultPort' of undefined
>     at new ClientRequest (_http_client.js:50:54)
>     at Agent.request (_http_agent.js:301:10)
>     at Object.exports.request (http.js:52:22)
>     at repl:1:17

Node v0.11.9 on OS X (via homebrew), q-io 1.10.6.

**Comment by kriskowal** [comment]
I saw this when trying out the unstable branch, but backed away slowly. I’m not sure whether this is an API change or a regression. Will have to compare notes with the good folks on joyent/node.

**Comment by kornelski** [comment]
Works in v0.11.12
