### ISSUE TITLE
Recommendations for hitting file limit on copyTree?

### ISSUE THREAD

**Issue by jsoverson** [kriskowal/q-io#75]
I'm not seeing a way to manage a directory copy with `copyTree()` where the number of open files may exceed the OS limit.

If i'm missing something, please let me know.

Is there a way to limit the number of copies happening at once?

**Comment by kriskowal** [comment]
Oh, that’s interesting. `open` does do an AIMD control on file descriptors, imposing a delay if the open fails due to a file descriptor limit. I presume that’s not working in this case.

**Comment by jsoverson** [comment]
doesn't seem to be on node 0.10.17 and mac osx 10.8.5, but i will keep poking.

**Comment by kriskowal** [comment]
It might be that mkdir is producing a different error code, or that my wrapping isn't adding the right properties to the error for the AIMD to catch it.

**Comment by kriskowal** [comment]
No, looks like `dampen` just looks for `code === "EMFILE"`, which should work for `mkdir`.

**Comment by jsoverson** [comment]
Yeah, boiling this down to basics doesn't show an issue with q-io. I assumed it was the issue because my use kept failing at the same number of file opens every time.

Closing.
