### ISSUE TITLE
odd behavior with copyTree

### ISSUE THREAD

**Issue by jsoverson** [kriskowal/q-io#76]
followup to https://github.com/kriskowal/q-io/issues/75

I put up a repository [here](https://github.com/jsoverson/qiotest) that replicates behavior i'm seeing that I can't track down for the life of me. Every time I try to copy the directory in the reposiroty via copyTree the resulting directory contains only a subset of the files and the promise never seems to fall through to either the fail or success case.

This is probably something obvious and i'm just overtired, but it's killing me.

You can run the test with `node test.js` which will just do the copy. Running `sh test.sh` will remove the targetDir, run the test, and then compare the resulting directories.

My output : 

``` shell
$ sh test.sh
Copying from /Users/jsoverson/development/src/qiotest/sourcedir to /Users/jsoverson/development/src/qiotest/targetDir
Only in sourceDir/js/vendor/ace/build/src: mode-properties.js
Only in sourceDir/js/vendor/ace/build/src: mode-python.js
Only in sourceDir/js/vendor/ace/build/src: mode-r.js
[... cut ...]
Only in sourceDir/js/vendor/ace/build/src: worker-lua.js
Only in sourceDir/js/vendor/ace/build/src: worker-php.js
Only in sourceDir/js/vendor/ace/build/src: worker-xquery.js
files in sourceDir : 265
files in targetDir : 198
```

If you move or remove enough files so there are 198 or less in sourceDir then the operation will succeed every time.

Tested and saw this same unexpected behavior on:
MBA w/ OSX 10.9.1 - node 0.10.15
MBP w/ OSX 10.8.5 - node 0.10.17

Tested and saw normal, expected behavior on:
Ubuntu 13.10 - node 0.10.15

**Comment by kriskowal** [comment]
Thanks. I’ll give this a shot and trace what's going on.

**Comment by jsoverson** [comment]
Any luck reproducing? If you can't reproduce it then i'll close it assuming it's some problem in my environments.

**Comment by kriskowal** [comment]
No, just haven’t had time to spare.

**Comment by sebz** [comment]
I've the same problem when trying to copy a folder containing a hierarchy of 290 folders and 927 files. All folders are copied but only 916 files...

I'll continue to investigate.

**Comment by kriskowal** [comment]
Thank you.

**Comment by kriskowal** [comment]
I believe I’ve found the problem. There was a race in copyTree.

https://github.com/kriskowal/q-io/pull/104

Please let me know if this solves your problem, if it no trouble.
