### ISSUE TITLE
req.headers.host do not include port number when using q-io('http')

### ISSUE THREAD

**Issue by CakeSpork** [kriskowal/q-io#77]
Hey guys,

I have a problem with q-io/http as I'm sending new request within the requested resource but req.headers.host turns out to be 'localhost' within it instead of 'localhost|:3000'. The request _does_ actually get sent to the correct URL, but the Express request object does not contain the correct headers when it ends up there.

For reference, the behavior does work as expected with require('request'). So I'm switching there for now, if I can not find a fix myself.

**Comment by CakeSpork** [comment]
I've traced the problem to http.js in this line:
request.headers.host = url.hostname; // FIXME name consistency

Seems... there were already people aware before this issue bothered me. Any reason that request.headers.host is not url.host?

**Comment by kriskowal** [comment]
We have fixed this problem in the latest v1 and v2 releases. My apologies for the delay.
