### ISSUE TITLE
Specify Q as a peer dependency

### ISSUE THREAD

**Issue by kornelski** [kriskowal/q-io#91]
Instead of specifying Q as a regular dependency, if you use [peer dependency](http://blog.nodejs.org/2013/02/07/peer-dependencies/):

``` js
  "peerDependencies": {
    "q": ">=0.9.7 <1.1"
  },
```

then installation of Q-IO won't install another copy of Q, but will reuse parent project's copy of Q.

This will make versions of promises consistent across Q and Q-IO, avoiding gotcha in https://github.com/kriskowal/q/issues/519

**Comment by Stuk** [comment]
Strictly Q-IO does depend on Q, and it isn't using the [plugin pattern](http://blog.nodejs.org/2013/02/07/peer-dependencies/) that peerDependencies are recommended for.

To avoid this situation you can use `npm dedupe` to pull all common dependencies up to the top level of `node_modules` (although this doesn't work with [Mr](https://github.com/montagejs/mr), but that just uses one version of each named dependency anyway).

Also, there is a big discussion about whether [`peerDependencies` should go away](https://github.com/npm/npm/issues/5080).

**Comment by stefanpenner** [comment]
I believe peerDependencies may become deprecated.

**Comment by kornelski** [comment]
Oh, bummer.
