### ISSUE TITLE
delete with files with wildcard

### ISSUE THREAD

**Issue by mlito** [kriskowal/q-io#92]
Hello 
Is there a way for deleting files with wild cards with using q-io ?
Tried remove function but does no seem to support wildcards 
Did I missed something ?
Thanks

**Comment by Stuk** [comment]
All of the functions take a single path. To delete multiple files you will need to iterate through an array of filenames. You can either use [`listTree`](https://github.com/kriskowal/q-io#listtreepath-guardpath-stat) with a guard function to get the list, or if you prefer to use wildcards then a module like [glob](https://www.npmjs.org/package/glob) is appropriate.
