### ISSUE TITLE
Create Collections documentation micro-site

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/q-io#94]
It should be easier to look up what collections implement a method and what methods are implemented by a collection. Create a micro-site that makes it easy to browse in both dimensions.

**Comment by Stuk** [comment]
I have some ideas and a bit of work towards doing this. 

I think the redis command documentation could be a good model http://redis.io/commands

**Comment by kriskowal** [comment]
@stuk, I can take care of content generation if you would like to take care of bringing it to life.

**Comment by Stuk** [comment]
Is this issue meant to be on the Collections repo?

**Comment by kriskowal** [comment]
Thanks. See montagejs/collections#95
